heestagram/heestagram/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
]

heestagram/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:post_id>/',views.detail,name='detail'),
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    path('<int:post_id>/edit/', views.edit, name='edit'),
    path('<int:post_id>/update/', views.update, name='update'),
    path('<int:post_id>/delete/', views.delete, name='delete'),
]

heestagram/posts/models.py
from django.db import models

# Create your models here.
class Post(models.Model):

    author = models.CharField(max_length=100)
    body = models.TextField()
    created_at = models.DateTimeField()

    def __str__(self):
        return f'{self.author}: {self.body}'

heestagram/posts/views.py
from django.shortcuts import render, redirect
from .models import Post
from django.utils import timezone


def index(request):
    posts = Post.objects.all()
    context = {'posts':posts}
    return render(request,'posts/index.html',context)

def detail(request, post_id):
    post = Post.objects.get(id=post_id)
    context = {'post':post}
    return render(request, 'posts/detail.html', context)

def new(request):
    return render(request, 'posts/new.html')

def create(request):
    author = request.POST['author']
    body = request.POST['body']
    post = Post(author=author, body=body, created_at=timezone.now())
    post.save()

    return redirect('posts:detail', post_id=post.id)

def edit(request, post_id):
    post = Post.objects.get(id=post_id)
    context = { 'post':post }
    return render(request, 'posts/edit.html', context)

def update(request, post_id):
    post = Post.objects.get(id=post_id)
    post.author = request.POST['author']
    post.body = request.POST['body']
    post.save()

    return redirect('posts:detail', post_id=post.id)

def delete(request, post_id):
    post = Post.objects.get(id=post_id)
    post.delete()

    return redirect('posts:index')

heestagram/posts/templates/posts/detail.html
{% extends "base.html" %}

{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'posts/style.css' %}" type="text/css" />
{% endblock %}

{% block content %}
    <div class="container">
        <h1>Post Detail</h1>
        {% if post %}
            <h2>작 성 자</h2>
            <p>{{ post.body }}</p>

            <h2>본 문</h2>
            <p>{{ post.body }}</p>

            <h2>게 시 일</h2>
            <p>{{ post.created_at }}</p>
        {% else %}
            <p>No Post.</p>
        {% endif %}

        <a href="{% url 'posts:index' %}">목 록</a>
        <a href="{% url 'posts:edit' post.id %}">수 정 하 기</a>
        <a href="{% url 'posts:delete' post.id %}">삭 제 하 기</a>
    </div>
{% endblock %}

heestagram/posts/templates/posts/edit.html
{% extends "base.html" %}

{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'posts/style.css' %}" type="text/css" />
{% endblock %}

{% block content %}
    <div class="container">
        <h1>Edit Post</h1>
        
        <form action="{% url 'posts:update' post.id %}" method="POST">
            {% csrf_token %}

            <h2>작 성 자</h2>
            <input type="text" name="author" value="{{ post.author }}" />

            <h2>본 문</h2>
            <textarea cols=40 rows=10 name="body">{{ post.body }}</textarea>

            <br>
            <input type="submit" value="수 정 하 기" />
        </form>

        <a href="{% url 'posts:index' %}">목 록</a>
    </div>
{% endblock %}

heestagram/posts/templates/posts/index.html
{% extends "base.html" %}

{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'posts/style.css' %}" type="text/css" />
{% endblock %}

{% block content %}
    <div class="container">
        <img src="../../static/posts/dami.jpg" />
        <h1>Posts</h1>
        
        {% if posts %}
            <table class="table">
                <thead class="thead-dark">
                    <tr>
                        <th>#</th>
                        <th>작 성 자</th>
                        <th>본 문</th>
                        <th>게 시 일</th>
                        <th>상 세</th>
                    </tr>
                </thead>
                <tbody>
                    {% for post in posts %}
                        <tr>
                            <th>{{ post.id }}</th>
                            <td>{{ post.author }}</td>
                            <td>{{ post.body }}</td>
                            <td>{{ post.created_at }}</td>
                            <td><a href="{% url 'posts:detail' post.id %}">보 기</a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>No Posts.</p>
        {% endif %}

        <a href="{% url 'posts:new' %}">글 쓰 기</a>
    </div>
{% endblock %}

heestagram/posts/templates/posts/new.html
{% extends "base.html" %}

{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'posts/style.css' %}" type="text/css" />
{% endblock %}

{% block content %}
    <div class="container">
        <h1>New Post</h1>
        <form action="{% url 'posts:create' %}" method="POST">
            {% csrf_token %}

            <h2>작 성 자</h2>
            <input type="text" name='author' />

            <h2>본 문</h2>
            <textarea cols="40" rows="10" name="body"></textarea>

            <br>
            <input type="submit" value="작 성 하 기" />
        </form>
        <a href="{% url 'posts:index' %}">목 록</a>
    </div>
{% endblock %}

heestagram/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <title>Heestagram</title>
    <link rel="stylesheet" href="{% static 'style.css' %}" type="text/css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    {% block style %}
    {% endblock %}
</head>

<body>
    <a href="{% url 'posts:run' %}">Run</a>
    {% block content %}
    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
        crossorigin="anonymous"></script>
</body>

</html>